name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main #Comment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Replace placeholder with secret
      run: |
        sed -i 's|REPLACE_WITH_IP|http://62.66.213.231:14718|g' script.js
        echo "Contents of script.js after replacement:"
        cat script.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
